#!/bin/bash
#PBS -l nodes=1:ppn=48
#PBS -l walltime=1:00:00
#PBS -q dssc 


cd $PBS_O_WORKDIR 
module load   openmpi/4.0.3/gnu/9.3.0

MOVES="1000000000" 

for procs in 1 4 8 12 16 20 24 28 32 36 40 44 48 ; do
for i in 1 2 3; do 
echo "executing on ", ${procs}, "  processors" 
/usr/bin/time -f %e mpirun  --mca btl '^openib' -np ${procs} mpi_pi.x $((${procs}*${MOVES})) >weakout.${procs} 2>> weakTIMES.dat
done 
done 
